name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # - name: Install dependencies
    #   run: |
    #     conda env update --file environment.yml --name base
    - name: Install datgen
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest